#ifndef __BIO_SENSORS_H__
#define __BIO_SENSORS_H__

/**
 * \file bio_sensors.h
 * \brief High-level biosensor driver for MAX30101 and MAX30205 on I2C3.
 */

#include <stdint.h>

#include "defines/MAX30101_reg.h"
#include "defines/MAX30205_reg.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef BIOSENSORS_MAX30101_ADDRESS_7BIT
#define BIOSENSORS_MAX30101_ADDRESS_7BIT           MAX30101_I2C_ADDRESS
#endif

#ifndef BIOSENSORS_MAX30205_ADDRESS_7BIT
#define BIOSENSORS_MAX30205_ADDRESS_7BIT           MAX30205_I2C_DEFAULT_7BIT_ADDRESS
#endif

#ifndef BIOSENSORS_PPG_SAMPLE_RATE_HZ
#define BIOSENSORS_PPG_SAMPLE_RATE_HZ              100U
#endif

#ifndef BIOSENSORS_PPG_SAMPLE_AVERAGE_COUNT
#define BIOSENSORS_PPG_SAMPLE_AVERAGE_COUNT        4U
#endif

#ifndef BIOSENSORS_PPG_EFFECTIVE_SAMPLE_RATE_HZ
#define BIOSENSORS_PPG_EFFECTIVE_SAMPLE_RATE_HZ \
    (BIOSENSORS_PPG_SAMPLE_RATE_HZ / BIOSENSORS_PPG_SAMPLE_AVERAGE_COUNT)
#endif

#ifndef BIOSENSORS_PPG_BUFFER_SIZE
#define BIOSENSORS_PPG_BUFFER_SIZE                 400U
#endif

#ifndef BIOSENSORS_MIN_PPG_SAMPLES_FOR_ESTIMATION
#define BIOSENSORS_MIN_PPG_SAMPLES_FOR_ESTIMATION  75U
#endif

#ifndef BIOSENSORS_MAX_FIFO_BATCH_SAMPLES
#define BIOSENSORS_MAX_FIFO_BATCH_SAMPLES          8U
#endif

#ifndef BIOSENSORS_MAX30101_FIFO_CONFIG_VALUE
#define BIOSENSORS_MAX30101_FIFO_CONFIG_VALUE \
    (MAX30101_FIFO_SAMPLE_AVG_4 | MAX30101_FIFO_ROLLOVER_DIS | MAX30101_FIFO_A_FULL_32_SAMPLES)
#endif

#ifndef BIOSENSORS_MAX30101_MODE_VALUE
#define BIOSENSORS_MAX30101_MODE_VALUE             MAX30101_MODE_SPO2
#endif

#ifndef BIOSENSORS_MAX30101_SPO2_CONFIG_VALUE
#define BIOSENSORS_MAX30101_SPO2_CONFIG_VALUE \
    (MAX30101_ADC_RANGE_4096NA | MAX30101_SAMPLE_RATE_100_SPS | MAX30101_PULSE_WIDTH_411_US)
#endif

#ifndef BIOSENSORS_MAX30101_RED_LED_CURRENT
#define BIOSENSORS_MAX30101_RED_LED_CURRENT        MAX30101_LED_CURRENT_12_6MA
#endif

#ifndef BIOSENSORS_MAX30101_IR_LED_CURRENT
#define BIOSENSORS_MAX30101_IR_LED_CURRENT         MAX30101_LED_CURRENT_12_6MA
#endif

#ifndef BIOSENSORS_MAX30101_INTERRUPT_ENABLE_1
#define BIOSENSORS_MAX30101_INTERRUPT_ENABLE_1 \
    (MAX30101_INT_EN_A_FULL | MAX30101_INT_EN_ALC_OVF)
#endif

#define BIOSENSORS_OK                              1U
#define BIOSENSORS_ERROR                           0U

#define BIOSENSORS_DATA_VALUE_COUNT                3U
#define BIOSENSORS_DATA_INDEX_HEART_RATE           0U
#define BIOSENSORS_DATA_INDEX_SPO2                 1U
#define BIOSENSORS_DATA_INDEX_TEMPERATURE          2U
#define BIOSENSORS_DATA_DECIMAL_SCALE              10U

uint8_t BioSensors_Init(void);
uint8_t BioSensors_InitMAX30101(void);
uint8_t BioSensors_InitMAX30205(void);
uint8_t BioSensors_Update(void);
uint8_t BioSensors_ReadData(uint8_t* data);
void BioSensors_NotifyPpgReady(void);

#ifdef __cplusplus
}
#endif

#endif /* __BIO_SENSORS_H__ */
